# -*- coding: utf-8 -*-
"""Zaigham-Dissertation.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Gqzimp1yt_jvos8Q05Ra19jI8aNq1YV
"""

import numpy as mpy
import scipy
from scipy import stats
import pandas as Pandi
from sklearn.metrics import confusion_matrix as ConfMat,classification_report as ClassRpt
from sklearn.model_selection import cross_val_predict as CrValPred,train_test_split as TrTsSp,ShuffleSplit as ShSp,learning_curve as LerCur,cross_val_score as CrValSc
from sklearn.model_selection import GridSearchCV as GrSrchCv
from sklearn.tree import DecisionTreeClassifier as DecTrCl
from sklearn.preprocessing import MinMaxScaler as MinMaxSc
import matplotlib.pyplot as MatPlt
from sklearn.linear_model import LogisticRegression as LogiReg
import seaborn as SeaBor
from sklearn.ensemble import RandomForestClassifier as RandFor
from sklearn.svm import SVC as SuppVecMach
from sklearn.neighbors import KNeighborsClassifier as KNearNeigh
import plotly.express as PlotEx

df = Pandi.read_csv("/content/drive/MyDrive/Zaigham-Dissertation/Dataset/World Happiness Report.csv")
df.head(7)

df.dtypes

df.shape

df.columns

MatPlt.figure(figsize=(17, 8))
SeaBor.heatmap(df.isnull())

df.isna().sum()

df.columns

df_null= Pandi.DataFrame(df.isna().sum())
df_null.columns =[ 'Missing Value Count']
df_null['Feature Name']=df.columns
df_null

SeaBor.barplot(data=df_null,y="Feature Name",x="Missing Value Count",orient="h")

df = df.dropna()
df.isna().sum()

df.shape

df.duplicated().value_counts()

df['Regional Indicator'].value_counts()

df['Country Name'].value_counts()

fig, ax = MatPlt.subplots(figsize=(10, 5))
SeaBor.heatmap(df.corr(), annot = True,ax=ax )
MatPlt.title("Relationship Between Features ")
MatPlt.show()

"""The correlation map shows that "Log GDP per Capita", "Social Support","Healthy Life Expectancy at Birth","Freedom to make choices" and positive effect has postive relationship with "Life Ladder". However, the Perception of corruption is negatively related with a value of -0.42. Lets confirm this with T-Test Analysis:"""

df.describe()

x = scipy.stats.pearsonr(df['Life Ladder'],  df['Log GDP Per Capita'])
x

"""Our Pearson Correlation Hypothesis is as Follows:

Ho - Columns do not correlate

Ha - Columns do Correlate

With P-value being 0.0, we can Reject Null Hypothesis (Ho)
"""

x = scipy.stats.pearsonr(df['Life Ladder'],  df['Social Support'])
x

"""Our Pearson Correlation Hypothesis is as Follows:

Ho - Columns do not correlate

Ha - Columns do Correlate

With P-value is near to 0.0, we can Reject Null Hypothesis (Ho)
"""

x = scipy.stats.pearsonr(df['Life Ladder'],  df['Healthy Life Expectancy At Birth'])
x

"""Our Pearson Correlation Hypothesis is as Follows:

Ho - Columns do not correlate

Ha - Columns do Correlate

With P-value is almost zero, we can Reject Null Hypothesis (Ho)
"""

x = scipy.stats.pearsonr(df['Life Ladder'],  df['Freedom To Make Life Choices'])
x

"""Our Pearson Correlation Hypothesis is as Follows:

Ho - Columns do not correlate

Ha - Columns do Correlate

With P-value is almost zero, we can Reject Null Hypothesis (Ho)
"""

x = scipy.stats.pearsonr(df['Life Ladder'],  df['Perceptions Of Corruption'])
x

def buildTarget(value):
    if value <= 5.4:
        return 0
    if value > 5.4:
        return 1

def buildTargetCat(value):
    if value <= 5.4:
        return 'Unhappy'
    if value > 5.4:
        return 'Happy'
target = df['Life Ladder'].apply(buildTarget)
target_cat = df['Life Ladder'].apply(buildTargetCat)

df['target']=target
df['target_cat']=target_cat

SeaBor.countplot(x='target_cat',data=df,palette="coolwarm_r")
MatPlt.title('Happiness Distribution', fontsize=14)
MatPlt.show()

df['Life Ladder'].hist()

df.head(30)

df['Life Ladder'].describe()

df_2022_happiest = df.groupby('Country Name')['Life Ladder'].mean().round(2).nlargest(5).reset_index()
fig, ax = MatPlt.subplots(figsize=(10, 5))
SeaBor.set(style = 'whitegrid')
palette = SeaBor.color_palette("Blues",n_colors=5)
palette.reverse()
SeaBor.barplot(ax =ax,data = df_2022_happiest , x = df_2022_happiest['Life Ladder'], y = df_2022_happiest['Country Name'],palette = palette)
ax.set_title(' 5 Most Happiest Countries of 2022')
ax.bar_label(ax.containers[0])

df_2022_saddest = df.groupby('Country Name')[['Country Name','Life Ladder']].mean().sort_values('Life Ladder', ascending=True).round(2).head(5).reset_index()
fig, ax = MatPlt.subplots(figsize=(10, 5))
SeaBor.set(style = 'whitegrid')
palette = SeaBor.color_palette("YlOrBr",n_colors=5)
palette.reverse()
SeaBor.barplot(ax =ax,data = df_2022_saddest , x = df_2022_saddest['Life Ladder'], y = df_2022_saddest['Country Name'],palette = palette)
ax.set_title(' 5 Least Happiest Countries of 2022')
ax.bar_label(ax.containers[0])

ss_2022_desc = Pandi.DataFrame(df.groupby('Country Name')[['Country Name','Social Support']].mean().sort_values('Social Support', ascending=False).round(2).head(5))
fig = PlotEx.bar(ss_2022_desc, x = ss_2022_desc.index, y = 'Social Support',
            title = 'Top Social Countrier (2022)', template = 'seaborn', color = ss_2022_desc.index, text = 'Social Support')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

ss_2022_asc = Pandi.DataFrame(df.groupby('Country Name')[['Country Name','Social Support']].mean().sort_values('Social Support', ascending=True).round(2).head(5))
fig = PlotEx.bar(ss_2022_asc, x = ss_2022_asc.index, y = 'Social Support',
            title = 'Lowest Social Countires (2022)', template = 'seaborn', color = ss_2022_asc.index, text = 'Social Support')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

cor_2022_desc = Pandi.DataFrame(df.groupby('Country Name')[['Country Name','Perceptions Of Corruption']].mean().sort_values('Perceptions Of Corruption', ascending=False).round(2).head(5))
fig = PlotEx.bar(cor_2022_desc, x = cor_2022_desc.index, y = 'Perceptions Of Corruption',
            title = 'Top 5 Most Corrupt Countires (2022)', template = 'seaborn', color = cor_2022_desc.index, text = 'Perceptions Of Corruption')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

cor_2022_asc = Pandi.DataFrame(df.groupby('Country Name')[['Country Name','Perceptions Of Corruption']].mean().sort_values('Perceptions Of Corruption', ascending=True).round(2).head(5))
fig = PlotEx.bar(cor_2022_asc, x = cor_2022_asc.index, y = 'Perceptions Of Corruption',
            title = 'Least Corrupt Countries (2022)', template = 'seaborn', color = cor_2022_asc.index, text = 'Perceptions Of Corruption')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

fig = PlotEx.choropleth(df, locations='Country Name', locationmode='country names',scope='world',color='Perceptions Of Corruption', color_continuous_scale= 'Viridis_r')
fig.update_layout(legend=dict(orientation="h"),
                  margin={'r':0,'t':0,'l':0,'b':0},
                  font=dict( family="Arial Black", size=14 ),
                  coloraxis_colorbar=dict(title = 'Corruption(2022)', ticks = 'outside', tickvals = [0,0.2,0.4,0.6,0.8,1.0], dtick = 7)
                  )
fig.show()

fig = PlotEx.choropleth(df, locations='Country Name', locationmode='country names',scope='world',color='Log GDP Per Capita', color_continuous_scale= 'Viridis_r')
fig.update_layout(legend=dict(orientation="h"),
                  margin={'r':0,'t':0,'l':0,'b':0},
                  font=dict( family="Arial Black", size=14 ),
                  coloraxis_colorbar=dict(title = 'Log GDP Per Capita (2022)', ticks = 'outside', tickvals = [6,8,10,12], dtick = 5)
                  )
fig.show()

fig = PlotEx.choropleth(df, locations='Country Name', locationmode='country names',scope='world',color='Social Support', color_continuous_scale= 'Viridis_r')
fig.update_layout(legend=dict(orientation="h"),
                  margin={'r':0,'t':0,'l':0,'b':0},
                  font=dict( family="Arial Black", size=14 ),
                  coloraxis_colorbar=dict(title = 'Social Supp (2022)', ticks = 'outside', tickvals = [0,0.2,0.4,0.6,0.8,1.0], dtick = 7)
                  )
fig.show()

fig = PlotEx.choropleth(df, locations='Country Name', locationmode='country names',scope='world',color='Social Support', color_continuous_scale= 'Viridis_r')
fig.update_layout(title = "Happines Comparison by Countries")
fig.update_layout(legend=dict(orientation="h"),
                  margin={'r':0,'t':0,'l':0,'b':0},
                  font=dict( family="Arial Black", size=14 ),
                  coloraxis_colorbar=dict(title = 'Life Ladder (2022)', ticks = 'outside', tickvals = [2,4,6,8], dtick = 4)
                  )
fig.show()

reg_ind_2022 = Pandi.DataFrame(df.groupby('Regional Indicator')[['Regional Indicator','Life Ladder']].mean().sort_values('Life Ladder', ascending=False).round(2).head(10))
fig = PlotEx.bar(reg_ind_2022, x = reg_ind_2022.index, y = 'Life Ladder',
            title = 'Happiness according to Regional Indicator - 2022', template = 'seaborn', color = reg_ind_2022.index, text = 'Life Ladder')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

reg_ind_2022 = Pandi.DataFrame(df.groupby('Regional Indicator')[['Regional Indicator','Social Support']].mean().sort_values('Social Support', ascending=False).round(2).head(10))
fig = PlotEx.bar(reg_ind_2022, x = reg_ind_2022.index, y = 'Social Support',
            title = 'Social Support according to Regional Indicator - 2022', template = 'seaborn', color = reg_ind_2022.index, text = 'Social Support')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

reg_ind_2022 = Pandi.DataFrame(df.groupby('Regional Indicator')[['Regional Indicator','Perceptions Of Corruption']].mean().sort_values('Perceptions Of Corruption', ascending=False).round(2).head(10))
fig = PlotEx.bar(reg_ind_2022, x = reg_ind_2022.index, y = 'Perceptions Of Corruption',
            title = 'Perceptions Of Corruption according to Regional Indicator - 2022', template = 'seaborn', color = reg_ind_2022.index, text = 'Perceptions Of Corruption')
fig.update_layout( font=dict( family="Arial Black", size=16 ), showlegend=False )
fig.show()

df.drop(['Country Name', 'Regional Indicator', 'Life Ladder','target_cat','target'], axis=1, inplace=True)

x_trn, x_valid, y_trn, y_valid = TrTsSp(df, target, test_size=.3)

print(f'x_trn: {x_trn.shape}, y_trn: {y_trn.shape}')
print(f'x_valid: {x_valid.shape}, y_valid: {y_valid.shape}')

scaler = MinMaxSc()

x_trn_scaled = scaler.fit_transform(x_trn)
x_valid_scaled = scaler.transform(x_valid)

modelLR=LogiReg()
CrValSc(modelLR, x_trn_scaled, y_trn, cv=5).mean().round(2)

modelRFC = RandFor(n_estimators=100, n_jobs=-1, random_state=23)
CrValSc(modelRFC, x_trn_scaled, y_trn, cv=5).mean().round(2)

modelSVC = SuppVecMach(kernel='rbf', C=1)
CrValSc(modelSVC, x_trn_scaled, y_trn, cv=5).mean().round(2)

modelKNN = KNearNeigh()
CrValSc(modelKNN, x_trn_scaled, y_trn, cv=5).mean().round(2)

modelDT = DecTrCl()
CrValSc(modelDT, x_trn_scaled, y_trn, cv=5).mean().round(2)

LR_params = {"penalty": ['l1', 'l2','elasticnet'], 'C': [ 0.01, 0.1, 1, 10, 100]}
grid_LR = GrSrchCv(LogiReg(), LR_params)
grid_LR.fit(x_trn_scaled, y_trn)
LR = grid_LR.best_estimator_
print("Logistic Regression:",LR)

KNN_params = {"n_neighbors": list(range(2,5,1)), 'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute']}

grid_KNN = GrSrchCv(KNearNeigh(), KNN_params)
grid_KNN.fit(x_trn_scaled, y_trn)
KNN = grid_KNN.best_estimator_
print("KNN:",KNN)

tree_params = {"criterion": ["gini", "entropy"], "max_depth": list(range(2,4,1)),
              "min_samples_leaf": list(range(5,7,1))}
grid_tree = GrSrchCv(DecTrCl(), tree_params)
grid_tree.fit(x_trn_scaled, y_trn)

DT = grid_tree.best_estimator_
print("Decision Tree:",DT)

rf_params = {"n_estimators"      : [10,20,30],
            "max_features"      : ["sqrt", "log2"],
            "min_samples_split" : [2,4,8],
            "bootstrap": [True, False]}
grid_rf = GrSrchCv(RandFor(), rf_params, n_jobs=-1, cv=5)
grid_rf.fit(x_trn_scaled, y_trn)

RF = grid_rf.best_estimator_
print("Random Forest:",RF)

SVC_params = {'C': [0.5, 0.7, 0.9, 1], 'kernel': ['rbf', 'poly', 'sigmoid', 'linear']}
grid_SVC = GrSrchCv(SuppVecMach(), SVC_params)
grid_SVC.fit(x_trn_scaled, y_trn)

SVC_best = grid_SVC.best_estimator_
print("Support Vector Machine:",SVC_best)

LR_score = CrValSc(LR, x_trn_scaled, y_trn, cv=5)
KNN_score = CrValSc(KNN, x_trn_scaled, y_trn, cv=5)
DT_score = CrValSc(DT, x_trn_scaled, y_trn, cv=5)
RF_score = CrValSc(RF, x_trn_scaled, y_trn, cv=5)
SVC_score = CrValSc(SVC_best, x_trn_scaled, y_trn, cv=5)

print('LR-:', round(LR_score.mean() * 100, 2), '%\n KNN-:', round(KNN_score.mean() * 100, 2), '%')
print('DT-:', round(DT_score.mean() * 100, 2), '% \n RF-:', round(RF_score.mean() * 100, 2), '%\n SVC-:', round(SVC_score.mean() * 100, 2), '%')

train_sizes, tr_rating, ts_rating = LerCur(LR, x_trn_scaled, y_trn, cv=None,n_jobs=1, train_sizes=mpy.linspace(.1, 1.0, 5))
tr_rating_mean = mpy.mean(tr_rating, axis=1)
tr_rating_std = mpy.std(tr_rating, axis=1)
ts_rating_mean = mpy.mean(ts_rating, axis=1)
ts_rating_std = mpy.std(ts_rating, axis=1)
MatPlt.fill_between(train_sizes, tr_rating_mean - tr_rating_std,
                  tr_rating_mean + tr_rating_std, alpha=0.1,
                  color="#E6644E")
MatPlt.fill_between(train_sizes, ts_rating_mean - ts_rating_std,
                  ts_rating_mean + ts_rating_std, alpha=0.1, color="#4E69E6")
MatPlt.plot(train_sizes, tr_rating_mean, 'o-', color="#E6644E",
          label="Training Rating")
MatPlt.plot(train_sizes, ts_rating_mean, 'o-', color="#4E69E6",
          label="Cross validation RAting")
MatPlt.suptitle("Learning Curve \n Logistic Regression", fontsize=14)
MatPlt.xlabel('Training Sample size')
MatPlt.ylabel('Rating')

train_sizes, tr_rating, ts_rating = LerCur(DT, x_trn_scaled, y_trn, cv=None,n_jobs=1, train_sizes=mpy.linspace(.1, 1.0, 5))
tr_rating_mean = mpy.mean(tr_rating, axis=1)
tr_rating_std = mpy.std(tr_rating, axis=1)
ts_rating_mean = mpy.mean(ts_rating, axis=1)
ts_rating_std = mpy.std(ts_rating, axis=1)
MatPlt.fill_between(train_sizes, tr_rating_mean - tr_rating_std,
                  tr_rating_mean + tr_rating_std, alpha=0.1,
                  color="#E6644E")
MatPlt.fill_between(train_sizes, ts_rating_mean - ts_rating_std,
                  ts_rating_mean + ts_rating_std, alpha=0.1, color="#4E69E6")
MatPlt.plot(train_sizes, tr_rating_mean, 'o-', color="#E6644E",
          label="Training score")
MatPlt.plot(train_sizes, ts_rating_mean, 'o-', color="#4E69E6",
          label="Cross-validation score")
MatPlt.suptitle("Decision Tree Learning Curve", fontsize=14)
MatPlt.xlabel('Training size')
MatPlt.ylabel('Score')

train_sizes, tr_rating, ts_rating = LerCur(RF, x_trn_scaled, y_trn, cv=None,n_jobs=1, train_sizes=mpy.linspace(.1, 1.0, 5))
tr_rating_mean = mpy.mean(tr_rating, axis=1)
tr_rating_std = mpy.std(tr_rating, axis=1)
ts_rating_mean = mpy.mean(ts_rating, axis=1)
ts_rating_std = mpy.std(ts_rating, axis=1)
MatPlt.fill_between(train_sizes, tr_rating_mean - tr_rating_std,
                  tr_rating_mean + tr_rating_std, alpha=0.1,
                  color="#E6644E")
MatPlt.fill_between(train_sizes, ts_rating_mean - ts_rating_std,
                  ts_rating_mean + ts_rating_std, alpha=0.1, color="#4E69E6")
MatPlt.plot(train_sizes, tr_rating_mean, 'o-', color="#E6644E",
          label="Training score")
MatPlt.plot(train_sizes, ts_rating_mean, 'o-', color="#4E69E6",
          label="Cross-validation score")
MatPlt.suptitle("Random Forest Learning Curve", fontsize=14)
MatPlt.xlabel('Training size')
MatPlt.ylabel('Score')

train_sizes, tr_rating, ts_rating = LerCur(SVC_best, x_trn_scaled, y_trn, cv=None,n_jobs=1, train_sizes=mpy.linspace(.1, 1.0, 5))
tr_rating_mean = mpy.mean(tr_rating, axis=1)
tr_rating_std = mpy.std(tr_rating, axis=1)
ts_rating_mean = mpy.mean(ts_rating, axis=1)
ts_rating_std = mpy.std(ts_rating, axis=1)
MatPlt.fill_between(train_sizes, tr_rating_mean - tr_rating_std,
                  tr_rating_mean + tr_rating_std, alpha=0.1,
                  color="#E6644E")
MatPlt.fill_between(train_sizes, ts_rating_mean - ts_rating_std,
                  ts_rating_mean + ts_rating_std, alpha=0.1, color="#4E69E6")
MatPlt.plot(train_sizes, tr_rating_mean, 'o-', color="#E6644E",
          label="Training score")
MatPlt.plot(train_sizes, ts_rating_mean, 'o-', color="#4E69E6",
          label="Cross-validation score")
MatPlt.suptitle("Support Vector Machine Learning Curve", fontsize=14)
MatPlt.xlabel('Training size')
MatPlt.ylabel('Score')

train_sizes, tr_rating, ts_rating = LerCur(KNN, x_trn_scaled, y_trn, cv=None,n_jobs=1, train_sizes=mpy.linspace(.1, 1.0, 5))
tr_rating_mean = mpy.mean(tr_rating, axis=1)
tr_rating_std = mpy.std(tr_rating, axis=1)
ts_rating_mean = mpy.mean(ts_rating, axis=1)
ts_rating_std = mpy.std(ts_rating, axis=1)
MatPlt.fill_between(train_sizes, tr_rating_mean - tr_rating_std,
                  tr_rating_mean + tr_rating_std, alpha=0.1,
                  color="#E6644E")
MatPlt.fill_between(train_sizes, ts_rating_mean - ts_rating_std,
                  ts_rating_mean + ts_rating_std, alpha=0.1, color="#4E69E6")
MatPlt.plot(train_sizes, tr_rating_mean, 'o-', color="#E6644E",
          label="Training score")
MatPlt.plot(train_sizes, ts_rating_mean, 'o-', color="#4E69E6",
          label="Cross-validation score")
MatPlt.suptitle("K Nearest Nieghbour Learning Curve", fontsize=14)
MatPlt.xlabel('Training size')
MatPlt.ylabel('Score')

LR_pred = CrValPred(LR, x_trn_scaled, y_trn, cv=5,
                             method="decision_function")

KNN_pred = CrValPred(KNN, x_trn_scaled, y_trn, cv=5)

SVC_pred = CrValPred(SVC_best, x_trn_scaled, y_trn, cv=5,
                             method="decision_function")

DT_pred = CrValPred(DT, x_trn_scaled, y_trn, cv=5)

RF_pred = CrValPred(RF, x_trn_scaled, y_trn, cv=5)

print("Logistic Regresssion has a accuracy score of ", round(LR_pred.mean(), 2) * 100, "%")
print("KNN has a accuracy score of", round(KNN_pred.mean(), 2) * 100, "%")
print("SVC has a accuracy score of", round(SVC_pred.mean(), 2) * 100, "%")
print("DT has a accuracy score of", round(DT_pred.mean(), 2) * 100, "%")
print("RF has a accuracy score of", round(RF_pred.mean(), 2) * 100, "%")

LR.fit(x_trn_scaled, y_trn)
y_pred_LR = LR.predict(x_valid_scaled)
LR_cf = ConfMat(y_valid, y_pred_LR )
fig, (ax1) = MatPlt.subplots(ncols=1, figsize=(5,5))
SeaBor.heatmap(LR_cf,
            xticklabels=['Unhappy', 'Happy'],
            yticklabels=['Unhappy', 'Happy'],
            annot=True,ax=ax1,
            linewidths=.2,linecolor="Darkblue", cmap="Blues")
MatPlt.title('Confusion Matrix', fontsize=14)
MatPlt.show()

KNN.fit(x_trn_scaled, y_trn)
y_pred_KNN = KNN.predict(x_valid_scaled)
KNN_cf = ConfMat(y_valid, y_pred_LR )
fig, (ax1) = MatPlt.subplots(ncols=1, figsize=(5,5))
SeaBor.heatmap(KNN_cf,
            xticklabels=['Unhappy', 'Happy'],
            yticklabels=['Unhappy', 'Happy'],
            annot=True,ax=ax1,
            linewidths=.2,linecolor="Darkblue", cmap="Blues")
MatPlt.title('Confusion Matrix', fontsize=14)
MatPlt.show()

RF.fit(x_trn_scaled, y_trn)
y_pred_RF = RF.predict(x_valid_scaled)
RF_cf = ConfMat(y_valid, y_pred_RF )
print('Confusion Matrix\n')
print(RF_cf)
SeaBor.heatmap(RF_cf, annot=True, cmap="Blues")

DT.fit(x_trn_scaled, y_trn)
y_pred_DT = DT.predict(x_valid_scaled)
DT_cf = ConfMat(y_valid, y_pred_DT )
print('Confusion Matrix\n')
print(DT_cf)
SeaBor.heatmap(DT_cf, annot=True, cmap="Blues")

SVC_best.fit(x_trn_scaled, y_trn)
y_pred_SVC = SVC_best.predict(x_valid_scaled)
SVC_cf = ConfMat(y_valid, y_pred_SVC )
print('Confusion Matrix\n')
print(SVC_cf)
SeaBor.heatmap(SVC_cf, annot=True, cmap="Blues")

print('\nClassification Report\n')
print(ClassRpt(y_valid, y_pred_LR, target_names=['Unhappy', 'Happy']))